version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: 101534641_comp3123_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: comp3123_assigment1
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: 101534641_comp3123_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - app-network

  app:
    build: .
    container_name: 101534641_comp3123_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/comp3123_assigment1
      JWT_SECRET: your_jwt_secret_key_here_change_in_production
      PORT: 3000
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
